### ISSUE TITLE
suggest_backports.py issues [moved from astropy/astropy#681]

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tools#10]
**I'm moving this issue which used to be in the core repo (https://github.com/astropy/astropy/issues/681). From @embray**

I'm working now on backporting a lot of the merged PRs for v0.2.x.  It's mostly going smoothly but I need to document a few issues that have cropped up:
1. There was apparently a manual merge of #629, though the script still picked that up as a merged PR. However, it failed to return the correct merge commit for that PR. Instead it returned the SHA for the last commit before the merge.  I'm not sure why that is but I suspect it could have something to do with how github handles the events on manually merged PRs.
2. If one runs the script multiple times between tags it still lists commits that have already been cherry-picked and backported. It's not clever enough to filter out all PRs that have already been backported. In particular, this can happen when commit message comparison fails, because sometimes when cherry-picking there will be a merge conflict, which causes the autogenerated commit message to append a list of files that conflicted.  This part of the commit messages needs to be ignored.
3. Turns out walking commits is even more subtle than I thought; I naively assumed GitHub's API would just automatically list commits in the order that they're shown in GitHub's GUI. But alas we have to write our own code to handle DAG walking.

**Comment by bsipocz** [comment]
I think this issue is now obsolete as we moved to use the pr_consistency scripts for the releases? Or are we still supposed to use suggest_backports?

**Comment by astrofrog** [comment]
Yep - let's remove that script first though

**Comment by pllim** [comment]
Can probably remove the script now that we use backport bot.

**Comment by pllim** [comment]
Superseded by #176 and I cannot find that script anymore.
