### ISSUE TITLE
Consider using batchpr for updating astropy-helpers

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tools#106]
Starting from the script to update the helpers, I made a mini-package called [batchpr](https://github.com/astrofrog/batchpr) that contains a lot of the overhead of forking, cloning, etc. and making it so scripts can just assume they are operating on checked out files - here's what the script to update astropy-helpers looks like with batchpr:

https://gist.github.com/astrofrog/f5e20c2e9e84ab97ff5433ef9b86b11a

So this is just a note that we could consider switching to using batchpr here to simplify things?

By the way, if we go this route, we could always put batchpr in the OpenAstronomy org alongside baldrick.

**Comment by bsipocz** [comment]
Nice! I suppose this will be the preferred way over https://github.com/astropy/astropy-procedures/pull/26 and such?

**Comment by pllim** [comment]
This can be closed now without further action.
