### ISSUE TITLE
List of things to include in next astropy-helpers/package template updates

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tools#108]
This issue is just a reminder of things we could include in the next batch updates for astropy-helpers and package-template files. Feel free to add more in comments (or edit this):

* [x] Update astropy-helpers
* [x] Remove ``ez_setup.py``
* [x] Update ``_astropy_init.py``
* [ ] Update ``setup.py``

Notify/open issues:
* [x] MPLBACKEND is now set to Agg, packages expecting interactive plotting should override it in .travis.yml
* [x] update travis matrix, at least jobs with NUMPY_VERSION<1.13 and ASTROPY_VERSION=stable
* [x] `sphinx-astropy` as dependency: https://github.com/astropy/astropy-procedures/issues/108#issuecomment-447880971
* [x] `six` not to be imported from astropy but directly

Next round of issues:
* [ ] usage of `_ASTROPY_SETUP_` and that whether that tries to import astropy at setup time or not https://github.com/astropy/astropy/pull/8402#discussion_r258379669

With helpers 3.2 update:
 - [ ] make a note that sphinx-astropy should be listed as a dependency for building the docs.

**Comment by bsipocz** [comment]
The first 2 can and will be dealt with the usual helpers update procedure. 

For the rest, it would be useful to list the stuff that we need to update specifically (a link to the relevant PR in the template would do)

**Comment by astrofrog** [comment]
@bsipocz - for ``_astropy_init.py`` I was thinking of just copying over the whole file from the template to make sure it's up to date, whatever people have in their package (rather than checking for specific changes)

**Comment by bsipocz** [comment]
oh. So you think it's safe to assume no one did any customization there? Probably that's a fair assumption though (or maybe there is an easy way to compare it to each and every version of that file from the package template, and if it's from any point in the past we can assume it's safe to update).

**Comment by astrofrog** [comment]
We can check for customizations of the file by comparing to hashes of past versions of that file. This is actually true for all files of the template in fact. I'll try writing a script soon that can do these kinds of checks.

**Comment by pllim** [comment]
I found that I also had to update RTD requirements file to include `sphinx-astropy` after update to `astropy-helpers` 3.1. Not sure how easy it is to hunt down some random RTD requirements file and update it properly; maybe just add a note in this same PR to remind maintainer to check it, is applicable.

**Comment by pllim** [comment]
> Notify/open issues

This part is done. 😉

**Comment by pllim** [comment]
Update: @bsipocz opened PRs to update `_astropy_init.py` for some(?) of the repos.

**Comment by bsipocz** [comment]
Yes, I've opened it for repos listed in `helpers_2.py`. Once we switch the package template to be python3 only (and tag it), I can open it for the rest of the repos in `helpers_3.py`, before that I feel it's counterproductive to switch them back to python2 supporting files.

**Comment by pllim** [comment]
This can be closed now without further action.
