### ISSUE TITLE
Add docstring checker

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-tools#11]
It would be great if there was an automatic docstring checker for Astropy and affiliated packages available.

See https://github.com/astropy/ccdproc/issues/338 as an example.

There's also examples in the Astropy core where a missing whitespace before a colon leads to the docstring not being rendered correctly:
http://docs.astropy.org/en/latest/api/astropy.io.ascii.Ipac.html#astropy.io.ascii.Ipac.write

<img width="324" alt="screen shot 2016-04-01 at 09 29 42" src="https://cloud.githubusercontent.com/assets/852409/14200604/521dee62-f7ec-11e5-801d-3a1f72a6ef39.png">

While I was writing this issue I remembered that I had thought of this before and found this tool which basically does it:
https://github.com/PyCQA/pydocstyle

What remains to be done is to make it work with our docstring format
https://github.com/PyCQA/pydocstyle/issues/129
and then to apply it to Astropy core and let affilated package authors know about it.

cc @bsipocz

**Comment by bsipocz** [comment]
A related issue in core https://github.com/astropy/astropy/issues/5504

**Comment by pllim** [comment]
We have RTD run now in PR that can turn warning into error.
