### ISSUE TITLE
Changelog-PR checker is not working for astroML

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#119]
Opening this as a reminder for self to fix the script, it somehow doesn't work for astroML. Recognizes the PRs, but the changelog parsing is messed up and reports everything as missing.

**Comment by bsipocz** [comment]
(Also, as a bonus, it would be great to make it possible to feed a local changelog to the script rather than what's on master on github, that case fixes could be checked incrementally without having to upload them).

**Comment by pllim** [comment]
The change log bot isn't here anymore.
