### ISSUE TITLE
Add scripts to make Tom R plots shown in Socorro meeting 2019

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-tools#146]
@astrofrog to add scripts used to make plots shown in "state of the core package" talk given in Astropy Coordination Meeting 2019 (Socorro, NM).

**Comment by bsipocz** [comment]
some of those scripts live here: https://github.com/astrofrog/astropy-graphs

**Comment by pllim** [comment]
I prefer Scientific Python devstats now.
