### ISSUE TITLE
Add a script that makes PRs updating the core package's helpers to make release process a bit faster

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-tools#15]
From @astrofrog in https://github.com/astropy/astropy/pull/5037#issuecomment-224520674:

> One additional script that would be useful (which I could write based on the one I did for the affiliated packages) is one that would make the PRs to the astropy core package to update the astropy-helpers in the master and maintenance branches (e.g. astropy/astropy#5040 and astropy/astropy#5041)

**Comment by eteq** [comment]
Although when I think about it I'm not sure this particular step is really worth automating more than other steps...?

**Comment by astrofrog** [comment]
Except it's kind of a pain and easy to automate ;)

**Comment by bsipocz** [comment]
Do we still want to do automate this? For the last few helpers releases, these PRs to the core was a way to test the helpers release candidate before actually doing the tagging and releasing. I don't see how we could avoid that kind of testing...

**Comment by astrofrog** [comment]
A better option to simplify the workflow would be to implement https://github.com/astropy/astropy-helpers/issues/350, after which we could have one of the travis builds use this option and use the latest developer version of the helpers (this means we can avoid doing the PR to astropy core with the pre-released helpers)

**Comment by pllim** [comment]
This can be closed now without further action.

**Comment by pllim** [comment]
We no longer use astropy-helpers.
