### ISSUE TITLE
Add hack in pr_consistency check to look for changelog entries without PR number

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#162]
This PR originally had the removal of both python37 and numpy 1.18, however currently it's not possible to add multiple changelog segments. As a workaround, multiple PRs have to be opened which is not desirable as they will conflict with each other, etc.

It's possible though to add an empty line, so we could just workaround towncrier and double check that changelog entries are separated by empty lines, and all entries have a PR number at the end of the last line.

So a PR could add multiple segments by separating them by a line, and at release time the scripts would notify the release manager to fix the rendered version by adding the PR number manually wherever it's missing.

**Comment by pllim** [comment]
Superseded by #176
