### ISSUE TITLE
Rename changelog scripts to be consistency scripts

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tools#20]
The 'changelog' scripts have evolved to be more than just about the changelog, and check the whole consistency of the pull requests, branches, backports, and changelog entry.

cc @eteq @bsipocz

**Comment by bsipocz** [comment]
I should try out those scripts next time, they look super useful. Thanks both of you for making them.

**Comment by bsipocz** [comment]
This can be close as #22 is merged.
