### ISSUE TITLE
MISC: add_to_changelog.py doesn't work for bugfix versions

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#30]
This is what I got when run the script after tagging v1.0.12. 

 * [ ] - there shouldn't be ``New Features``, but ``Bug fixes`` only.
 * [ ] - even for major release, there should be a ``Bug fixes`` session
 * [ ] - the section headers should probably come from the major release, or even probably guessing from the content of the packagename directory?

```
+v1.0.13 (unreleased)
+--------------------
+
+New Features
+^^^^^^^^^^^^
+
+- ``astropy.convolution``
+
+- ``astropy.coordinates``
+
+- ``astropy.io.fits``
+
+- ``astropy.io.votable``
+
+- ``astropy.utils``
+
+API Changes
+^^^^^^^^^^^
+
+- ``astropy.convolution``
+
+- ``astropy.coordinates``
+
+- ``astropy.io.fits``
+
+- ``astropy.io.votable``
```

**Comment by pllim** [comment]
This script is now under "discontinued usage" folder.
