### ISSUE TITLE
PR_CONSISTENCY: Better way to handle non astropy-core repos

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#41]
The branch checks are still not working perfectly for non astropy-core repos. E.g for astropy-helpers there was no v0.1.x, v0.2.x, v0.3.x branches, yet the report mention those (probably using release dates for astropy-core). I don't have time to look into this now, so opening this as a reminder:

![screen shot 2017-05-29 at 17 44 26](https://cloud.githubusercontent.com/assets/6788290/26557096/cf06850e-4496-11e7-80fe-517ea9b1c692.png)

**Comment by eteq** [comment]
@bsipocz - I think you didn't intend #42 to fully close this, but if you think it's good enough, feel free to close this now.

**Comment by bsipocz** [comment]
Nope, #42 doesn't fix it all yet, e.g. ``4.check_consistency.py`` is still full of hard wired values for branches and manually merged PRs, etc.

**Comment by pllim** [comment]
Superseded by #176
