### ISSUE TITLE
PR_CONSISTENCY: Major releases are not recognized

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#43]
Major releases (e.g. 1.3 or 2.0) is not recognized properly by the PR scripts. Somehow this doesn't affect astropy-core, but there are issues with e.g. astropy-helpers. 1) when milestone and version doesn't agree as v2.0.0 vs v2.0, the other example is that PRs 277 and 279 are indeed included in release 1.3, but are not recognized as such:

![screen shot 2017-05-29 at 19 27 28](https://cloud.githubusercontent.com/assets/6788290/26559063/21927c98-44a5-11e7-9cdd-e31802578d2e.png)

**Comment by bsipocz** [comment]
Ah, OK. So there will be no solution for the second issue as the backport commits were backported as part of the ``tmp-release-v1.3`` branch as thus the script doesn't see them directly on the branch.
![screen shot 2017-05-29 at 19 32 43](https://cloud.githubusercontent.com/assets/6788290/26559136/a0c130b8-44a5-11e7-8952-4ec56add601d.png)

I guess we need to update the release instructions to avoid making this tmp branch, here: http://docs.astropy.org/en/latest/development/releasing.html#coordinating-astropy-and-astropy-helpers-releases

**Comment by bsipocz** [comment]
Part of the issue is solved, it was a stupid typo in the milestone ``v.2.0.0`` vs ``v2.0.0``. The other part is still valid though, merge of merges are still not recognized.

**Comment by pllim** [comment]
Superseded by #176
