### ISSUE TITLE
PR_CONSISTENCY: command line option to override LAST_MODIFIED_DATE

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#46]
https://github.com/astropy/astropy-helpers/pull/314 has been remilestoned, but it happened after branching. However the release scripts doesn't picked this change up as I've already run them after the branching.

Would be nice to have a command line option to override the last modified date in the script to force rescanning some of the PRs.

**Comment by bsipocz** [comment]
Oh, a bigger issue is that, even after deleting all the jsons, it doesn't recognize that astropy/astropy-helpers#314 is included in 2.0.x branch even though it's milestoned to 3.0

**Comment by pllim** [comment]
Superseded by #176
