### ISSUE TITLE
PR_CONSISTENCY: Deal with manual merges

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#59]
Due to the extensive refactoring in 3.0, we started to have bug fix PRs that are not backportable to 2.0.x. However the issue they fix are there in 2.0.x, and they simply just need a manual backport. 

Ideally the script should be able to handle these cases, notify if they are not yet backported, but stay quiet if a counterpart PR against the 2.0.x branch is merged. In worst case scenario the PR number will be simply added to the manual backport dictionary, better case would be a cleaver automated way.

**Comment by pllim** [comment]
Superseded by #176
