### ISSUE TITLE
Write docs on how various CI services were set up

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-tools#75]
There is now a document stub which should be filled out explaining how we set up the various CI services:

https://github.com/astropy/astropy-procedures/tree/master/documents

**Comment by bsipocz** [comment]
don't we have it covered in the package-template docs either directly there or in the main astropy one?

**Comment by astrofrog** [comment]
I'll double check, the idea here was to discuss things not at the config file level but e.g whether AppVeyor was set up under a special Astropy account or whether anyone can do it, or whether they need to be added to the team

**Comment by bsipocz** [comment]
oh, OK, that's most probably hasn't been mentioned anywhere. (Neither that we have asked for an old image and use that org wide as the default).

**Comment by pllim** [comment]
I don't think we need this anymore?
