### ISSUE TITLE
Colourful logging and print version for helpers update

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-tools#89]
Currently the update script is rather verbose and so useful information can easily lost.

E.g. it appeared that `astropy-healpix` is not receiving helpers updates as it had a "newer" version than v2.0.6 in the form of of a 6 month old v3.0.dev. It would be useful that in cases like this a final logfile was created with name of package and current version of helpers. 
Alternatively a the `Repository astropy-healpix already has an up-to-date astropy-helpers` message could be printed to stdout with a distinctive colour, and also provide the version number rather than just a hash.

**Comment by pllim** [comment]
This can be closed now without further action.
